# This was when the platform was simply a sliding box on the ground
moving_landing_base:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    slider_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: slider_joint
        pid: {p: 20, i: 0.2, d: 10}